### ISSUE TITLE
Where does audiocodec come from?

### ISSUE THREAD

**Issue by jmiller656** [korneelvdbroek/mp3net#1]
Hi! This is a really cool repo. I saw you imported some stuff from `audiocodec` in the following line:

```python
from audiocodec.mdctransformer import MDCTransformer
```

Where can I find this library?

**Comment by korneelvdbroek** [comment]
`audiocodec` contains a set of audio specific functions (psychoacoustic filters and mdct transformation) which I split off into a [separate repo](https://github.com/korneelvdbroek/audiocodec).

**Comment by jmiller656** [comment]
Awesome, thanks! 

By the way, I just wanted to say. The quality of this code is **AMAZING**. This is some of the best/neatest ML code I've ever read, I appreciate that.
