### ISSUE TITLE
preprocessing

### ISSUE THREAD

**Issue by materialvision** [korneelvdbroek/mp3net#2]
Hi, thanks for this nice repo. I wanted to test out training on a folder with audio, but do you have an easy way to preprocess audiofiles into tfrecords? Any hint on how to use the dataprep.py?

**Comment by korneelvdbroek** [comment]
Hi, I anonymized the Colab script I use for preprocessing and added it [here](https://github.com/korneelvdbroek/mp3net/blob/main/colab/dataprep.ipynb) to the repo. Hope this helps!

**Comment by materialvision** [comment]
Thank you, I will give it a go!
